### PR TITLE
New feature: playlists

### PR DESCRIPTION
**Pull request by ndunand**
@sdiemer @fthiery as discussed today

### CODE REVIEW

**Comment by ndunand** [comment]
Ah ! @fthiery  @sdiemer 

Just added a functional lazy-loading of the iframes: 1st iframe is loaded immediately, subsequent ones loaded when tab clicked.

**Comment by sdiemer** [comment]
A big thank you for the help on this feature.
I will take a look on the code next week, I'm too busy this week.
Regards

**Comment by sdiemer** [comment]
I took a look on the code a week ago, I will have to implement the title retrieval using the postMessage API available in the player since Nudgis 12.3.0.
Unfortunately, I will not have the time to work on this until we have released some features on Nudgis that we have to make available during this summer.
I will let you know when I can work on this.

Regards

**Comment by ndunand** [comment]
Ok.
Not so sure the postMessage API is the way to go, as the iframes are loaded on-demand (lazy-loading), so they are not available when the playlist is first loaded.
It would be bad for performance to force loading of all iframes on pageload.

**Comment by sdiemer** [comment]
> Not so sure the postMessage API is the way to go, as the iframes are loaded on-demand (lazy-loading), so they are not available when the playlist is first loaded. It would be bad for performance to force loading of all iframes on pageload.

The purpose of my suggestion to use postMessage API is to avoid any configuration, but you're right, it requires that all iframes are loaded on page load and that's not good for performance.
The way you have chosen, to handle the requests to Nudgis in the backend, is the best for performance.

**Comment by ndunand** [comment]
Yes indeed it's a tradeoff between convenience and performance.

However, if the configuration is skipped (i.e. no API endpoint nor API key is set in the filter config), then the tabs still display a numbered list: 1,2,3,...

**Comment by sdiemer** [comment]
I will open a new pull request in order to be able to change the code to handle the conflict with the latest changes (it is not possible to [change the source branch](https://stackoverflow.com/questions/42381557/changing-source-branch-for-pr-on-github)).

**Comment by sdiemer** [comment]
https://github.com/UbiCastTeam/moodle-filter_ubicast/pull/4

**Comment by sdiemer** [comment]
Hello,
I have merged the pull request #2, I close this one.
A big thank you for the contribution :)

**Pull request closed without merging**
